"""npc generator"""

def main():
    return 'dmpc'


def generate_rumor():
    subject = [
               "The king",
               "The queen",
               "The local miller",
               "The local blacksmith",
               "A retired adventurer",
               "A famous assassin",
               "An influential guildmaster",
               "The mayor",
               "An up-and-coming young knight",
               "The high priest of Bhaal",
               "A powerful Drow Matron",
               "A wicked wizard",
               "The Knight-Lord of a local order of Paladins",
               "Strahd von Zarovich",
               "A militant emperor in the West",
               "A dragon-tamer in the mountains",
               "The local dragon",
               "An Orc warlord",
               "One of the party members",
               "An ancient pharaoh",
               "A popular gladiator",
               "A teamster who is a local legend for reckless driving",
               "The crown prince",
               "A master alchemist",
               "A high-ranking Hobgoblin commander",
               "An elven sage",
               "The duchess",
               "The duke",
               "The local priest",
               "An eccentric inventor",
               "The town lunatic",
               "A notorious pirate captain",
               "A travelling monk",
               "A famous mystic",
               "The housekeeper of a local hostel",
               "A Viking king",
               "The Great Chief of Ogres",
               "A famous trap-maker",
               "An influential politician",
               "The town beggar",
               "The Princess",
               "A newly-appointed Lady Knight of the region",
               "A newly-appointed Lord Knight of the region",
               "The Caesar of Minotaurs",
               "The local weaponsmith",
               "The BBEG",
               "The mysterious man with a long, silver beard and a ragged black cloak",
               "The mysterious woman with long, silver hair and an old-fashioned scarlet cloak",
               "The local tobacco merchant",
               "The kingpin of a crime ring",
               "The head of a Tarrasque-worshiping cult",
               "A vicious Manticore baron",
               "A highly sought-after tailor",
               "A highly sough-after baker",
               "A highly sought-after physician",
               "Every gravedigger in the entire region",
               "The king's two-year-old son",
               "A kuo-toa diplomat",
               "The Bloodlord of Vampires",
               "A necromancer",
               "The court magician",
               "A boatman on the local river",
               "A mason building the king's new palace",
               "A great athlete",
               "The head of a not-so-secret society",
               "The local innkeeper",
               "A zombie who was voted in as townmaster",
               "An Elvish king",
               "The Lord of a druidic circle",
               "The new 8-year-old king",
               "A famous painter",
               "One of the PCs' mentor",
               "A famous evangelist",
               "A Gorgon beauty guru",
               "The yuan-ti God-King",
               "A powerful Unseelie Fey",
               "A goblin warlord",
               "The editor of a local newspaper",
               "The game warden",
               "The king's butler",
               "A renowned golem-building wizard",
               "A great General",
               "A local veteran and war hero",
               "A folk-music writer",
               "The street-lamp lighter",
               "The street sweeper",
               "The chimney-sweep",
               "The harsh boss of a local factory",
               "A far-sailing explorer, back in town after an expedition",
               "A local archaeologist",
               "The Witchfinder General",
               "The Protector Angel of the nearest large city",
               "A powerful Seelie Fey",
               "The Iron Emperor of Dwarves",
               "The Erlking of a local band of monster-hunters",
               "A fashion icon",
               "The Grand Duke of the Society for the Preservation of Gnomish Vocabulistics and Grammar",
               "A famous daredevil",
               "The leader of a mostly harmless local cult",
               "The leader of an extremely harmful local cult"
               ]
    action = [
              "disgusted by {} ",
              "Hates {} ",
              " Weeps tears of joy for... ",
              " Breaks down laughing at the thought of... ",
              " Is worryingly obsessed with... ",
              " Spent all their money on... ",
              " Has asked the Church to forbid... ",
              " Has asked the Church to demand... ",
              " Has formed a society based around... ",
              " Has led an expedition to... ",
              " Once enjoyed... ",
              " Has recently picked up... ",
              " Demands someone to explain to them what all the fuss is with... ",
              " Has forbid the mere mention of... ",
              " Commissioned several murals of... ",
              " Sentenced convicts to.... ",
              " Named their new yacht.... ",
              " Disowned their child for the child's becoming addicted to... ",
              " Is hopelessly addicted to... ",
              " Has challenged any takers to a contest of... ",
              " Has started a scandal by... ",
              " Has completely ignored the issues of... ",
              " Got drunk and admitted to... ",
              " Firmly denies that they have ever... ",
              " Is hosting a costume ball themed around... ",
              " Suffers nightmares about... ",
              " Wants advice on how to go about... ",
              " Tossed someone out of a window for daring to malign... ",
              " Hired bards to sing the praises of... ",
              " Is trying to quit... ",
              " Divorced their spouse to spend more time... ",
              " Wandered into the desert with the intent of... ",
              " Demanded that any honest man would never stoop to... ",
              " Stole a carriage to go... ",
              " Has paid people to stop... ",
              " Has demanded, against ancient tradition, that they be allowed to... ",
              " Carved a statue of themselves... ",
              " Has never even tried... ",
              " Is ignoring the obvious solution to their current problem, .... ",
              " Gives up all hope for the world when they think about... ",
              " Turns into a panda whenever they try... ",
              " Has been cursed by a witch to ceaselessly wander through the forest, ... ",
              " Loves their spouse, but more so, ... ",
              " Used magic to make 100 people go... ",
              " Got drunk and went... ",
              " Spent all their inheritance on... ",
              " Might start a war over... ",
              " Tattooed themselves with scenes of... ",
              " Ceaselessly talks about... ",
              " Ran 40 miles so as not to be late for... ",
              " Wears their finest clothes to... ",
              " Believes in the Gods but more so in... ",
              " Doesn't even understand... ",
              " Pays good money for people to compete at ... for their amusement. ",
              " Found an ancient urn, worth thousands, depicting... ",
              " Insists that it is a genteel pursuit to... ",
              " Is causing trouble for everyone by... ",
              " Sees it as unseemly to... ",
              " Frequently enjoys... ",
              " Is enraged by... ",
              " Is saddened by... ",
              " Got sick while... ",
              " Broke their foot while... ",
              " Died while... ",
              " Proposed to their true love whilst... ",
              " Is terrified by the prospect of... ",
              " Believes it is a grievous sin to... ",
              " Nearly started a revolution while a nobleman was... ",
              " Clapped a man in irons for trying to... ",
              " Is only ever gladdened by... ",
              " Fully intends to kill their rival, making it look like an accident that occurred while they were... ",
              " Has changed their main pursuit to.... ",
              " Denies claims that they ever..., despite solid evidence. ",
              " Has a long history in their family of... ",
              " Was nearly assassinated while... ",
              " Explodes with fury when others ask if they intend to... ",
              " Is enchanted to slowly levitate into the sky should they ever try... ",
              " Has ordered a local noble to stop... ",
              " Is haunted by the ghosts of those who died such that they could... ",
              " Has cured themselves of a terrible illness by simply... ",
              " Arose from the grave when they heard their relatives were... instead of attending their funeral. ",
              " Wrote long and vivid books on the subject of... ",
              " Will not so much as get out of bed until they... ",
              " Rises bright and early to... ",
              " Trained several hawks for the purposes of... ",
              " Breaks into song and dance randomly to distract people from their habit of... ",
              " Says they would rather die than... ",
              " Dreams of... ",
              " Has no appetite on days when they haven't... ",
              " Hired adventurers to... ",
              " Hired a wizard to help them with... ",
              " Built an entire facility dedicated to... ",
              " Used slaves and prisoners for... ",
              " Threw themselves into a lake after a long day of... ",
              " Hosted a banquet in celebration of their successful quest of... ",
              " Frequently boasts about how good they are at... ",
              " Demands that nobody but themselves be allowed to... ",
              " Prays to the gods for success in... ",
              " Recommends that pregnant women try... "
              ]
    thing = [
              " Digging pit traps. ",
              " Minting gold pieces. ",
              " Falling out of windows. ",
              " Human sacrifice. ",
              " Setting things on fire. ",
              " Raiding small settlements. ",
              " Eating pastries shaped like sacred icons. ",
              " Swimming around in pools of oil. ",
              " Riding horses. ",
              " Painting pictures. ",
              " Sabotaging other people's carriages. ",
              " Hurling radishes at beggars. ",
              " Stepping on people's toes. ",
              " Doing nothing. ",
              " Shutting up. ",
              " Feeling confident. ",
              " Running over small and fluffy animals. ",
              " Tipping over Dominoes. ",
              " Going on shopping sprees. ",
              " Punching sacks of potatoes. ",
              " Building elaborate but useless siege engines. ",
              " Having rap-battles with pixies. ",
              " Doing the conga. ",
              " Convincing other people to do the conga. ",
              " Building extremely comfortable couches. ",
              " Building up an immunity to every kind of poison they can find. ",
              " Studying vaccination. ",
              " Learning how to fly. ",
              " Burying dead bodies. ",
              " Juggling swords. ",
              " Juggling. ",
              " Being a clown. ",
              " Buying elaborate tricorn hats. ",
              " Ringing people's doorbells and running away. ",
              " Writing terrible books. ",
              " Reading scandalous magazines. ",
              " Praising themselves. ",
              " Cow-tipping. ",
              " Throwing china plates across rooms. ",
              " Plating things with solid gold. ",
              " Getting involved in tangled love-triangles. ",
              " Awarding themselves trophies for things they never did. ",
              " Giving long and elaborate speeches. ",
              " Getting drunk. ",
              " Getting high. ",
              " Throwing knives at pictures of their enemies. ",
              " Mixing fake blood in excessive quantities. ",
              " Fighting Treants. ",
              " Inventing new kinds of forks. ",
              " Grave robbing. ",
              " Burning down mansions. ",
              " Writing speeches full of innuendos for pastors. ",
              " Recycling old furniture. ",
              " Playing war-games. ",
              " Playing card games. ",
              " Playing dice games. ",
              " Making loaded dice. ",
              " Starting bar fights. ",
              " Making theatrical declarations of war against nonexistent countries. ",
              " Completely ignoring real-world geography. ",
              " Crashing the economy. ",
              " Hurling cinder-blocks at passerby. ",
              " Teaching Trolls calligraphy. ",
              " Insulting Dragons. ",
              " Writing dramatic Last Wills for themselves regarding fictitious deaths. ",
              " Murdering people to start a murder-investigation romantic drama. ",
              " Brooding on rooftops. ",
              " Doing tuck-and-rolls into wedding ceremonies. ",
              " Hiding treasures in local dungeons. ",
              " Doing the Charleston at funerals. ",
              " Starting moshpits at children's cello recitals. ",
              " Headbanging to the church choir. ",
              " Rolling themselves down hills. ",
              " Giving excessive amounts of charity. ",
              " Joining every secret society they can find. ",
              " Doing somersaults when excited. ",
              " Shooting people with crossbows. ",
              " Designing a new national flag for their country every day, and sending it to the nobility for approval. ",
              " Taming Mimics. ",
              " Hitting people over the head with bar stools. ",
              " Wearing cool cloaks. ",
              " Spontaneously combusting. ",
              " Drag-racing in carriages. ",
              " Trying to ride Displacer Beasts. ",
              " Trying to ride Owlbears. ",
              " Jumping out at people from behind corners and shouting "Boo!" ",
              " Rigging old castles to explode. ",
              " Making silly faces at high-ranking clergy. ",
              " Smoking far too many cigarettes than is advisable. ",
              " Writing fake magazine articles describing wars between closely allied countries. ",
              " Deep-frying books. ",
              " Writing dictionaries of all 89 dialects of Abyssal. ",
              " Pulling pranks. ",
              " Breeding new horses. ",
              " Conducting unethical scientific experiments. ",
              " Building exact replicas of small villages, then demanding that all the villagers from that village move to the replica. ",
              " Giving themselves ludicrous new titles. ",
              " Carrying far too many canes. "]
    return "".join(random.choice(subject),random.choice(action),random.choice(thing))

